# X500 - Introdução à Ciência de Dados

Prof. Erneson Alves de Oliveira<br>
Programa de Pós-Graduação em Informática Aplicada<br>
Universidade de Fortaleza

# 2 Introdução ao Pandas

![picture](https://drive.google.com/thumbnail?id=1UzNXA9dEa9ynMRWH5PqgUUAk-dWSKkWN&sz=w600)

https://pandas.pydata.org

## 2.5 Ordenando e filtrando

In [3]:
import pandas as pd

d = {'apples': {'A': 3, 'B': 2, 'C': 0, 'D': 1},
     'oranges': {'A': 0, 'B': 3, 'C': 7, 'D': 2},
     'bananas': {'A': 1, 'B': 3, 'C': 5, 'D': 4},
     'avocados': {'A': 9, 'B': 0, 'C': 0, 'D': 1}}

df = pd.DataFrame(d)
print(df)

   apples  oranges  bananas  avocados
A       3        0        1         9
B       2        3        3         0
C       0        7        5         0
D       1        2        4         1

In [ ]:
print(df.sort_index(axis = 0, ascending = False))
print(df.sort_index(axis = 0))

   avocados  apples  oranges  bananas
D         1       1        2        4
C         0       0        7        5
B         0       2        3        3
A         9       3        0        1
   avocados  apples  oranges  bananas
A         9       3        0        1
B         0       2        3        3
C         0       0        7        5
D         1       1        2        4

In [4]:
#print(df.sort_values(by = 'oranges'))
# print(df.sort_values(by = ['avocados', 'apples']))
print(df.sort_values(by = 'oranges', axis = 0, ascending= False))

   apples  oranges  bananas  avocados
C       0        7        5         0
B       2        3        3         0
D       1        2        4         1
A       3        0        1         9

In [ ]:
print(df.sort_values(by = 'A', axis = 1))

   oranges  bananas  apples  avocados
A        0        1       3         9
B        3        3       2         0
C        7        5       0         0
D        2        4       1         1

In [6]:
print(df)

   avocados  apples  oranges  bananas
A         9       3        0        1
B         0       2        3        3
C         0       0        7        5
D         1       1        2        4

In [5]:
df.sort_values(by = 'B', axis = 1, inplace = True)
print(df)

# df0 = df.sort_values(by = ['B', 'C'], axis = 1)
# print(df0)
# print(df)

   avocados  apples  oranges  bananas
A         9       3        0        1
B         0       2        3        3
C         0       0        7        5
D         1       1        2        4

In [8]:
cols = ['bananas', 'avocados']
df[cols]

   bananas  avocados
A        1         9
B        3         0
C        5         0
D        4         1

In [9]:
df

   avocados  apples  oranges  bananas
A         9       3        0        1
B         0       2        3        3
C         0       0        7        5
D         1       1        2        4

In [ ]:
print(df.oranges)

A    0
B    3
C    7
D    2
Name: oranges, dtype: int64

In [ ]:
print(df['oranges'])

A    0
B    3
C    7
D    2
Name: oranges, dtype: int64

In [ ]:
print(df['oranges'])
print(df['oranges']['A'])

A    0
B    3
C    7
D    2
Name: oranges, dtype: int64
0

In [ ]:
print(df.oranges)
# print(df.oranges[0:2])
# print(df[0:3])

df['oranges'][0] = 99
print(df)

A    0
B    3
C    7
D    2
Name: oranges, dtype: int64
   apples  oranges  bananas  avocados
A       3       99        1         9
B       2        3        3         0
C       0        7        5         0
D       1        2        4         1

In [ ]:
# linha = df.loc['A']
# print(type(linha))
# print(linha)

# linhas = df.loc['B':'C', ['oranges', 'bananas']]
# print(type(linhas))
# print(linhas)

# print(df.loc['B', 'oranges']) # df.at['A', 'oranges']

In [ ]:
# print(df.iloc[3])
# print(df.iloc[0:2, 0:2])

# print(df.iloc[2, 2]) # df.iat[2,2]

## 2.6 Combinando colunas

In [10]:
d = {'apples': {'A': 3, 'B': 2, 'C': 0, 'D': 1},
     'oranges': {'A': 0, 'B': 3, 'C': 7, 'D': 2},
     'bananas': {'A': 1, 'B': 3, 'C': 5, 'D': 4},
     'avocados': {'A': 9, 'B': 0, 'C': 0, 'D': 1}}

df = pd.DataFrame(d)
print(df)

   apples  oranges  bananas  avocados
A       3        0        1         9
B       2        3        3         0
C       0        7        5         0
D       1        2        4         1

In [ ]:
print(df['bananas'] + df['oranges'])
print(df)

A     1
B     6
C    12
D     6
dtype: int64
   apples  oranges  bananas  avocados
A       3        0        1         9
B       2        3        3         0
C       0        7        5         0
D       1        2        4         1

In [ ]:
df['bananas_oranges'] = df['bananas'] + df['oranges']
print(df)

   apples  oranges  bananas  avocados  bananas_oranges
A       3        0        1         9                1
B       2        3        3         0                6
C       0        7        5         0               12
D       1        2        4         1                6

In [11]:
df['bananas_oranges'] = round(df['bananas'] / df['oranges'], 2)
print(df)

   apples  oranges  bananas  avocados  bananas_oranges
A       3        0        1         9              inf
B       2        3        3         0             1.00
C       0        7        5         0             0.71
D       1        2        4         1             2.00

## 2.7 Descrevendo uma planilha

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   apples           4 non-null      int64
 1   oranges          4 non-null      int64
 2   bananas          4 non-null      int64
 3   avocados         4 non-null      int64
 4   bananas_oranges  4 non-null      float64
dtypes: float64(1), int64(4)
memory usage: 192.0+ bytes

In [ ]:
df.describe()

         apples  oranges   bananas  avocados  bananas_oranges
count  4.000000  4.00000  4.000000  4.000000         4.000000
mean   1.500000  3.00000  3.250000  2.500000              inf
std    1.290994  2.94392  1.707825  4.358899              NaN
min    0.000000  0.00000  1.000000  0.000000         0.714286
25%    0.750000  1.50000  2.500000  0.000000         0.928571
50%    1.500000  2.50000  3.500000  0.500000         1.500000
75%    2.250000  4.00000  4.250000  3.000000              inf
max    3.000000  7.00000  5.000000  9.000000              inf

In [ ]:
df.head(3)

   avocados  apples  oranges  bananas
A         9       3        0        1
B         0       2        3        3
C         0       0        7        5

In [ ]:
df.tail(3)

   avocados  apples  oranges  bananas
B         0       2        3        3
C         0       0        7        5
D         1       1        2        4

In [ ]:
df

   apples  oranges  bananas  avocados  bananas_oranges
A       3        0        1         9              inf
B       2        3        3         0         1.000000
C       0        7        5         0         0.714286
D       1        2        4         1         2.000000

# Referências

[1] <a> https://docs.python.org/pt-br/3/tutorial/</a>

[2] <a> https://pandas.pydata.org/</a>

[3] Joel Grus. Data science from scratch: first principles with python. O'Reilly Media, 2019.